#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# 프리뷰 Supabase 프로젝트 (운영과 분리된 전용 프로젝트).
PREVIEW_REF="${PREVIEW_REF:-glwypjldklwpgdtymktm}"
PRODUCTION_REF="sbutbsghcxmxmxgrshwq"
VERCEL_SCOPE="sangwopark19icons-1055s-projects"
VERCEL_PROJECT="icons-ip"
SUPABASE_DASHBOARD="https://supabase.com/dashboard/project/${PREVIEW_REF}"
VERCEL_ENV_URL="https://vercel.com/${VERCEL_SCOPE}/${VERCEL_PROJECT}/settings/environment-variables"

# 이 위저드가 다루는 값은 CI와 Vercel에만 들어간다. 로컬 `.env`에 쓰지 않는다 —
# 로컬 개발은 `supabase start`가 띄우는 로컬 스택을 쓴다.
ENV_FILE="/dev/null"

if [[ "$PREVIEW_REF" == "$PRODUCTION_REF" ]]; then
  printf '%s\n' "PREVIEW_REF가 운영 프로젝트와 같습니다. 중단합니다." >&2
  exit 1
fi

# vercel_env NAME ENVIRONMENT VALUE — Vercel 환경변수를 sensitive로 덮어쓴다.
# pipeline.yml의 CRON_SECRET 동기화와 같은 방식(`--force`)이라 rm 없이 교체된다.
vercel_env() {
  local name="$1" environment="$2" value="$3"
  if [[ ! -f .vercel/project.json ]]; then
    SKIPPED+=("Vercel $environment env $name (먼저 'npx vercel link'을 실행하세요)")
    warn "Vercel 프로젝트가 연결되지 않았습니다 — 'npx vercel link' 후 다시 실행하세요"
    return 0
  fi
  if printf '%s' "$value" \
    | npx --yes vercel env add "$name" "$environment" --sensitive --force --yes \
      --scope "$VERCEL_SCOPE" >/dev/null 2>&1; then
    printf '  %s✓ set%s Vercel %s env %s\n' "$GREEN" "$RESET" "$environment" "$name"
    return 0
  fi
  SKIPPED+=("Vercel $environment env $name")
  warn "Vercel $environment env $name 설정 실패 — 대시보드에서 직접 넣어주세요"
  return 0
}

banner "프리뷰 Supabase 환경 구성 (icons-ip-preview)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "프리뷰 DB 비밀번호 → GitHub secret"
say "main 배포 뒤 shared preview main을 같은 migration·seed로 맞출 때 쓰는 비밀번호입니다."
note "운영 DB 비밀번호가 아닙니다. 프리뷰 프로젝트($PREVIEW_REF) 것만 다룹니다."
note "PR별 isolated branch는 이 비밀번호를 공유하지 않고 Branch API 연결 정보를 씁니다."
open_url "${SUPABASE_DASHBOARD}/settings/database"
step "Database password 섹션에서 'Reset database password'를 누릅니다."
step "생성된 비밀번호를 복사합니다. 이 화면을 벗어나면 다시 볼 수 없습니다."
warn "안전한 곳(비밀번호 관리자)에도 함께 보관하세요."
ask_secret PREVIEW_DB_PASSWORD "복사한 비밀번호를 붙여넣으세요:"
if [[ -z "$PREVIEW_DB_PASSWORD" ]]; then
  SKIPPED+=("GitHub secret SUPABASE_PREVIEW_DB_PASSWORD")
  warn "비어 있어 건너뜁니다 — PR preview는 가능하지만 main→shared preview 동기화가 실패합니다."
else
  set_secret SUPABASE_PREVIEW_DB_PASSWORD "$PREVIEW_DB_PASSWORD"
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "프리뷰 API 키 복사"
say "Vercel Preview의 안전한 baseline을 parent preview로 맞출 키 두 개입니다."
note "CI 배포는 shared main 또는 isolated branch의 키를 API로 다시 읽어 이 값을 동적으로 덮습니다."
open_url "${SUPABASE_DASHBOARD}/settings/api-keys"
step "publishable key(브라우저에 노출되는 공개 키)를 복사합니다."
ask PREVIEW_PUBLISHABLE_KEY "publishable key:"
step "secret key(sb_secret_…)를 Reveal한 뒤 복사합니다."
note "legacy 'service_role' JWT도 동작하지만 새 프로젝트는 sb_secret_ 형식을 쓴다."
warn "이 키는 RLS를 우회합니다. 저장소·채팅·명령 인자에 남기지 마세요."
ask_secret PREVIEW_SERVICE_ROLE_KEY "secret key (sb_secret_… 또는 service_role JWT):"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "공유 service role key에서 Preview 스코프 떼어내기"
say "Production SUPABASE_SERVICE_ROLE_KEY는 Production 스코프에만 있어야 합니다."
say "Preview baseline은 parent preview key를 별도 레코드로 사용합니다."
warn "이 단계만 대시보드에서 해야 합니다. CLI로 지우면 레코드 전체가 사라져 운영 키까지 잃습니다."
open_url "$VERCEL_ENV_URL"
step "SUPABASE_SERVICE_ROLE_KEY 행을 Edit합니다."
step "Environments에서 Preview 체크를 해제하고 Production만 남긴 뒤 Save합니다."
if confirm "Preview 체크를 해제했습니까?"; then
  vercel_env SUPABASE_SERVICE_ROLE_KEY preview "$PREVIEW_SERVICE_ROLE_KEY"
else
  SKIPPED+=("SUPABASE_SERVICE_ROLE_KEY Preview 분리 — 대시보드에서 Preview 해제 후 프리뷰 키를 새로 추가")
  warn "건너뜁니다. 수동/예외 배포의 baseline이 production key일 수 있으므로 반드시 분리하세요."
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Vercel Preview 환경변수를 프리뷰 프로젝트로 돌리기"
say "URL·publishable key baseline을 parent preview로 두고, 공개 화면도 Supabase를 읽게 합니다."
note "정상 GitHub Actions 배포는 PR mode에 따라 main 또는 pr-N 값을 build/runtime에 주입합니다."
note "ICONS_PROTOTYPE은 건드리지 않습니다 — 홍실 프로토타입 공유 배포가 그 값만 읽습니다."
vercel_env NEXT_PUBLIC_SUPABASE_URL preview "https://${PREVIEW_REF}.supabase.co"
if [[ -n "$PREVIEW_PUBLISHABLE_KEY" ]]; then
  vercel_env NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY preview "$PREVIEW_PUBLISHABLE_KEY"
else
  SKIPPED+=("Vercel Preview env NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY")
  warn "publishable key가 비어 있어 건너뜁니다."
fi
vercel_env ICONS_CATALOG_SOURCE preview "supabase"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "구성 확인"
say "CI가 볼 값들이 실제로 들어갔는지 확인합니다."
if gh secret list 2>/dev/null | grep -q '^SUPABASE_PREVIEW_PROJECT_ID'; then
  printf '  %s✓%s GitHub secret SUPABASE_PREVIEW_PROJECT_ID\n' "$GREEN" "$RESET"
else
  warn "GitHub secret SUPABASE_PREVIEW_PROJECT_ID 없음 — PR preview 배포를 skip합니다"
fi
if gh secret list 2>/dev/null | grep -q '^SUPABASE_PREVIEW_DB_PASSWORD'; then
  printf '  %s✓%s GitHub secret SUPABASE_PREVIEW_DB_PASSWORD\n' "$GREEN" "$RESET"
else
  warn "GitHub secret SUPABASE_PREVIEW_DB_PASSWORD 없음 — main→shared preview 동기화가 실패합니다"
fi
say ""
say "Vercel Preview 스코프:"
npx --yes vercel env ls preview --scope "$VERCEL_SCOPE" 2>/dev/null \
  | grep -E 'SUPABASE|ICONS_CATALOG_SOURCE|ICONS_PROTOTYPE' || warn "vercel env ls 실패 — 대시보드에서 확인하세요"
say ""
note "Auth Site URL·redirect allow-list는 workflow가 맞춥니다(scripts/sync-supabase-auth.mjs) — 손댈 필요 없습니다."
say ""
say "남은 일 — 프리뷰 배포를 한 번 돌려서 실제로 프리뷰 DB를 보는지 확인합니다:"
note "  1) PR의 CI를 rerun 하거나 새 커밋을 올립니다"
note "  2) deploy-supabase-preview summary가 shared main 또는 isolated pr-N인지 봅니다"
note "  3) 배포 URL로 번들을 grep해 운영 ref가 없는지 확인합니다:"
note "     README '프리뷰 환경 → 구성 확인' 절의 명령"
note "  4) DB 변경 PR이면 Supabase Branch 목록의 pr-N과 summary ref가 같은지 확인합니다"

finish
