export const PAYMENT_OUTCOMES = [
  'approved',
  'declined',
  'canceled',
  'unknown',
  'needs_review',
] as const;

export type PaymentOutcome = (typeof PAYMENT_OUTCOMES)[number];
/**
 * DB enum `public.payment_provider`와 같은 축이다. `bank_transfer` attempt는
 * 게이트웨이 seam(prepare/confirm/refund)을 타지 않지만, 원장의 provider 축은
 * DB enum과 어긋나면 안 된다 — attempt·payment 행을 읽는 코드가 같은 타입을 쓴다.
 */
export type PaymentProvider = 'toss' | 'korpay' | 'bank_transfer';
export type PaymentPurpose = 'order' | 'ticket' | 'prize_sale';

export interface PaymentAttempt {
  readonly id: string;
  readonly provider: PaymentProvider;
  readonly purpose: PaymentPurpose;
  readonly refId: string;
  readonly amount: number;
  readonly currency: string;
  readonly idempotencyKey: string;
  readonly providerOrderId: string;
  readonly providerProductCode: string;
  readonly expiresAt: string;
}

export type CheckoutAction =
  | {
      readonly kind: 'form_post';
      readonly url: string;
      readonly fields: Readonly<Record<string, string>>;
    }
  | {
      readonly kind: 'redirect';
      readonly url: string;
    }
  | {
      readonly kind: 'client_sdk';
      readonly payload: Readonly<Record<string, string | number | boolean>>;
    };

export interface PreparedCheckout {
  readonly attemptId: string;
  readonly provider: PaymentProvider;
  readonly action: CheckoutAction;
  /**
   * Opaque, single-use callback proof generated by the provider adapter.
   * The checkout module stores only its digest before returning the action.
   */
  readonly callbackNonce: string;
  readonly expiresAt: string;
}

export interface PaymentReturnInput {
  readonly attempt: PaymentAttempt;
  readonly idempotencyKey: string;
  readonly providerOrderId: string;
  readonly callbackNonce: string;
  readonly providerPayload: unknown;
}

export interface PaymentProviderEvidence {
  readonly providerPaymentKey?: string;
  readonly providerTransactionId?: string;
  readonly providerApprovalReference?: string;
  readonly resultCode?: string;
  readonly paymentMethod?: string;
  readonly maskedPaymentMethod?: string;
  readonly approvedAt?: string;
}

export interface PaymentOperationOutcome {
  readonly attemptId: string;
  readonly provider: PaymentProvider;
  readonly outcome: PaymentOutcome;
  readonly reasonCode?: string;
  readonly evidence?: PaymentProviderEvidence;
}

export type ConfirmOutcome = PaymentOperationOutcome;
export type ReconcileOutcome = PaymentOperationOutcome;

export interface PaymentRefundRequest {
  readonly attempt: PaymentAttempt;
  readonly idempotencyKey: string;
  readonly amount: number;
  readonly reason: string;
}

export interface RefundOutcome extends PaymentOperationOutcome {
  readonly refundedAmount?: number;
}

export interface PaymentGateway {
  prepare(attempt: PaymentAttempt): Promise<PreparedCheckout>;
  confirm(returnInput: PaymentReturnInput): Promise<ConfirmOutcome>;
  reconcile(attempt: PaymentAttempt): Promise<ReconcileOutcome>;
  refund(request: PaymentRefundRequest): Promise<RefundOutcome>;
}
