-- ============================================================================
-- ICONS · 클레임 도메인(취소·반품·교환)과 수단별 환불 실행 (#252)
--
-- 지금까지 있던 것은 "청약철회(취소)" 하나뿐이었다. 교환은 개념이 없었고 반품
-- 입고 확인은 승인 버튼에 암묵적으로 흡수돼 있었다(#176 D11). 스마트스토어의
-- 취소·반품·교환 3화면과 절차(요청→수거→입고→처리)를 카피하되, 주문 단위 전액
-- 원칙(약관 제16조)은 그대로 둔다.
--
-- ## 테이블을 새로 만들지 않는 이유
--
-- order_cancellation_requests를 rename하거나 새 테이블로 쪼개면, 이 테이블을
-- 본문 텍스트로 참조하는 함수 10여 개(request/decide/finalize/complete/
-- needs_review/manual recovery/account deletion/settle/dispatch 게이트)를 전부
-- 재생성해야 한다. 프리런치라 데이터는 비어 있어도 그 재생성 자체가 이번 변경의
-- 가장 큰 위험이다. 테이블명을 유지하고 컬럼을 넓힌다.
--
-- ## status와 stage — 왜 두 컬럼인가
--
-- 새 상태(in_review·collecting·collected·on_hold)를 status CHECK에 그냥 넣으면
-- 기존 게이트 12곳이 조용히 뚫린다. 그것들은 전부
-- `status in ('requested','processing','needs_review')` 리터럴로 "활성 요청"을
-- 판정한다 — admin_update_order_status(배송 전이 차단),
-- cancel_order_with_provider_evidence(웹훅 즉시취소 차단),
-- settle_delivered_orders(자동 거래확정 차단),
-- private.account_deletion_blockers(탈퇴 차단),
-- request_order_cancellation(중복 접수 차단), 부분 unique 인덱스(주문당 1건).
-- collecting 상태의 반품 클레임이 그 리터럴에 걸리지 않으면, 회수 중인 주문을
-- 어드민이 발송하고 웹훅이 취소하고 잡이 거래확정한다.
--
-- 그래서 절차 상태기계는 `stage`에 두고, `status`는 그 기계의 **레거시 투영**으로
-- 남긴다. 두 개의 상태기계가 아니라 하나의 기계와 하나의 파생값이다 —
-- 아래 CHECK가 불일치를 금지하고, 트리거가 레거시 writer의 status 변경을 stage로
-- 자동 승격한다(그래서 기존 함수를 한 줄도 고치지 않아도 두 값이 갈라지지 않는다).
--
--   stage                      →  status (레거시 투영)
--   ------------------------------------------------------
--   requested                  →  requested   (접수)
--   in_review                  →  requested   (검토 중)
--   collecting                 →  requested   (수거 중)
--   collected                  →  requested   (입고 확인)
--   on_hold                    →  requested   (운영 보류 — 재개 가능)
--   processing                 →  processing  (환불/재출고 실행 중)
--   needs_review               →  needs_review(provider 정합화 실패)
--   completed                  →  completed
--   rejected                   →  rejected
--
-- needs_review와 on_hold는 다른 개념이다. needs_review는 결제사 원장과 로컬 장부가
-- 어긋나 자동 정합화가 실패한 상태(기계가 푼다)이고, on_hold는 반품 배송비 미정산·
-- 연락 두절처럼 사람이 판단할 운영 보류다. 합치면 자동 복구 대상 큐와 사람 판단
-- 큐가 섞인다.
--
-- ## 환불계좌 보관 — #208 미응답에 대한 안전 기본값
--
-- questionnaire #208("환불계좌 암호화·보관기간")은 아직 답이 없다. 답을 기다리며
-- 수집을 미루면 무통장 환불 경로 자체가 없으므로, 가장 보수적인 가정으로 먼저
-- 만들고 답이 오면 좁힌다:
--   · 원문은 private 스키마의 별도 테이블에만 둔다(service_role 전용, staff 읽기
--     표면 없음). public 조인 대상이 아니므로 실수로 목록에 섞일 수 없다.
--   · 화면에는 마스킹 값만 나간다. 마스킹은 저장 시점에 만들어 원문 없이도 읽힌다.
--   · 환불 완료 30일 뒤 원문을 파기한다(purge_expired_claim_refund_accounts).
--     30일은 카드사·은행 재확인 요청이 들어올 수 있는 실무 창을 최소로 잡은 값이며,
--     #208의 답이 더 짧은 기간을 정하면 그 값으로 줄인다.
-- 이 가정은 #208 코멘트에도 남긴다.
--
-- ## 재고 복원과 카드팩 회수는 여기서 하지 않는다
--
-- 그 두 부수효과는 finalize_order_cancellation_with_provider_evidence 한 곳에만
-- 있다. 클레임 완료는 기존 정합화 경로(legacy Toss = 오케스트레이터, Korpay =
-- finalize_goods_manual_payment_recovery)를 그대로 타고, 그 경로가 요청을
-- completed로 닫는다. 이 파일의 환불 원장 RPC는 "완료" 기록을 클레임이 이미
-- completed일 때만 허용한다 — 돈이 돌아갔다고 적으면서 재고가 안 돌아오는 조합을
-- DB가 거절한다.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. 알림 타입 확장
-- ---------------------------------------------------------------------------
-- lib/notifications.ts의 NotificationType union과 같은 목록이어야 한다.
-- 한 곳만 바꾸면 알림이 CHECK로 막히거나(DB) 타입이 좁아 화면이 못 읽는다(앱).
alter table public.notifications
  drop constraint notifications_type_check;
alter table public.notifications
  add constraint notifications_type_check check (
    type in (
      'order_paid',
      'order_shipping',
      'order_delivered',
      'draw_ticket_issued',
      'drop_published',
      'event_published',
      'announcement',
      'inquiry_answered',
      'claim_updated'
    )
  );

-- ---------------------------------------------------------------------------
-- 2. 클레임 도메인 일반화
-- ---------------------------------------------------------------------------

-- 클레임번호. 주문번호(uuid 뒤 8자)와 달리 운영자가 전화로 부르는 값이라
-- 문의(#253)와 같은 정수 시퀀스를 쓴다.
alter table public.order_cancellation_requests
  add column reference bigint generated by default as identity;
alter table public.order_cancellation_requests
  add constraint order_cancellation_requests_reference_unique unique (reference);

alter table public.order_cancellation_requests
  add column claim_type text not null default 'cancel',
  add column stage text not null default 'requested',
  -- v1은 항상 null이다(주문 단위 전액 · 약관 제16조). 품목 단위 클레임(v2)으로
  -- 가는 문만 열어 둔다 — nullable이 아니면 v2에서 백필이 필요해진다.
  add column order_item_id uuid references public.order_items(id) on delete set null,
  add column hold_reason text,
  add column held_at timestamptz,
  -- 보류를 풀면 어디로 돌아가는가. 기억하지 않으면 재개가 항상 requested로
  -- 되감겨 이미 끝난 수거를 다시 시킨다.
  add column held_from text,
  add column collecting_at timestamptz,
  -- SLA의 기산점. 약관 제16조 "반환받은 날부터 3영업일"이 여기서 시작한다.
  -- stage가 processing으로 넘어가도 이 값은 남아 타이머가 계속 유효하다.
  add column collected_at timestamptz,
  add column reship_carrier text,
  add column reship_tracking_number text,
  add column reshipped_at timestamptz;

-- 컬럼 기본값('requested')은 이미 종결된 행에도 그대로 들어간다. 투영 CHECK를
-- 걸기 전에 기존 status를 stage로 옮긴다 — 순서를 뒤집으면 프리런치가 아닌
-- 환경에서 마이그레이션이 CHECK 위반으로 통째로 실패한다.
update public.order_cancellation_requests
set stage = status
where status <> 'requested';

alter table public.order_cancellation_requests
  add constraint order_cancellation_requests_claim_type_check
  check (claim_type in ('cancel', 'return', 'exchange'));

alter table public.order_cancellation_requests
  add constraint order_cancellation_requests_stage_check
  check (stage in (
    'requested',
    'in_review',
    'collecting',
    'collected',
    'on_hold',
    'processing',
    'needs_review',
    'completed',
    'rejected'
  ));

-- stage → status 투영. 이 제약이 "두 컬럼이지만 상태기계는 하나"를 강제한다.
alter table public.order_cancellation_requests
  add constraint order_cancellation_requests_stage_projection_check
  check (
    case stage
      when 'processing' then status = 'processing'
      when 'needs_review' then status = 'needs_review'
      when 'completed' then status = 'completed'
      when 'rejected' then status = 'rejected'
      else status = 'requested'
    end
  );

alter table public.order_cancellation_requests
  add constraint order_cancellation_requests_hold_reason_check
  check (
    hold_reason is null
    or (btrim(hold_reason) = hold_reason and length(hold_reason) between 10 and 200)
  );

-- 보류에는 사유가 반드시 있다. 사유 없는 보류는 구매자에게 설명할 수 없다.
alter table public.order_cancellation_requests
  add constraint order_cancellation_requests_hold_reason_present_check
  check (stage <> 'on_hold' or hold_reason is not null);

-- 운송장 형식은 orders_tracking_number_check와 같다. 재출고도 같은 택배사
-- 레지스트리로 조회 URL을 만들므로 형식이 갈라지면 링크가 깨진다.
alter table public.order_cancellation_requests
  add constraint order_cancellation_requests_reship_tracking_check
  check (
    reship_tracking_number is null
    or reship_tracking_number ~ '^[A-Z0-9]{8,30}$'
  );

-- 재출고 운송장은 택배사와 번호가 함께 있거나 함께 없다. 한쪽만 남으면
-- 배송 조회 링크를 만들 수 없다.
alter table public.order_cancellation_requests
  add constraint order_cancellation_requests_reship_pair_check
  check ((reship_carrier is null) = (reship_tracking_number is null));

-- 재출고는 교환 전용이다. 반품·취소에 운송장이 붙으면 환불과 재출고가 동시에
-- 일어난 것처럼 보인다.
alter table public.order_cancellation_requests
  add constraint order_cancellation_requests_reship_type_check
  check (claim_type = 'exchange' or reship_tracking_number is null);

-- 주문당 활성 클레임 1건. 새 stage가 전부 status='requested'로 투영되므로
-- 기존 부분 인덱스 정의를 그대로 두어도 정확하다 — 정의를 다시 적어 의도를
-- 남기고, 나중에 status 목록을 손대는 사람이 이 주석을 보게 한다.
--   (수거 중인 반품이 있는데 취소 클레임이 또 접수되는 구멍을 막는다)

create index order_cancellation_requests_claim_queue_idx
  on public.order_cancellation_requests (claim_type, stage, requested_at desc);

/*
 * 레거시 writer가 status만 바꿔도 stage가 따라간다.
 *
 * admin_decide_order_cancellation · complete_order_cancellation_request ·
 * mark_order_cancellation_needs_review · admin_begin_order_cancellation_reconcile ·
 * finalize_goods_manual_payment_recovery는 전부 status만 쓴다. 이 트리거가 없으면
 * 그 함수들이 CHECK 위반으로 실패하거나(투영 불일치) 두 값이 갈라진다.
 *
 * 반대 방향(새 RPC)은 stage와 status를 함께 명시하므로 이 트리거가 덮어쓰지
 * 않는다 — stage가 이미 바뀐 UPDATE는 그대로 통과시킨다.
 */
create or replace function private.project_order_claim_stage()
returns trigger
language plpgsql
volatile
security definer
set search_path = ''
as $function$
begin
  -- INSERT: 레거시 경로는 status만 준다(예: 20260714190001의 needs_review 이관).
  -- stage는 컬럼 기본값 'requested'로 채워지므로 그대로 두면 투영 CHECK를 어긴다.
  -- stage를 명시한 호출자(새 RPC)는 건드리지 않는다.
  if tg_op = 'INSERT' then
    if new.stage is not distinct from 'requested'
      and new.status is distinct from 'requested'
    then
      new.stage := new.status;
    end if;
    return new;
  end if;

  if new.status is distinct from old.status
    and new.stage is not distinct from old.stage
  then
    new.stage := case new.status
      when 'processing' then 'processing'
      when 'needs_review' then 'needs_review'
      when 'completed' then 'completed'
      when 'rejected' then 'rejected'
      -- requested로 되돌리는 레거시 경로(정합화 재시도)는 절차를 처음으로
      -- 감지 않는다. 보류가 아니었다면 검토 단계로 돌려 놓는다.
      else case
        when old.stage in ('collecting', 'collected', 'on_hold') then old.stage
        else 'requested'
      end
    end;
  end if;

  return new;
end;
$function$;

create trigger trg_order_cancellation_requests_stage_projection
before insert or update on public.order_cancellation_requests
for each row execute function private.project_order_claim_stage();

revoke all on function private.project_order_claim_stage()
  from public, anon, authenticated, service_role;

-- 새 컬럼 중 구매자가 읽어도 되는 것만 컬럼 grant에 더한다. hold_reason은
-- 알림 본문으로 전달하고 원문 열람은 열지 않는다 — 운영 메모가 그대로 노출되면
-- 내부 판단 근거가 새어 나간다.
grant select (
  reference,
  claim_type,
  stage,
  collecting_at,
  collected_at,
  reship_carrier,
  reship_tracking_number,
  reshipped_at
) on table public.order_cancellation_requests to authenticated;

-- ---------------------------------------------------------------------------
-- 3. 환불계좌 — service_role 전용 격리
-- ---------------------------------------------------------------------------
-- public 스키마에 두지 않는다. private은 Data API에 노출되지 않으므로 RLS가
-- 뚫려도 브라우저가 이 테이블에 닿을 수 없다(payment_provider_evidence 선례).
create table private.claim_refund_accounts (
  claim_id uuid primary key
    references public.order_cancellation_requests(id) on delete cascade,
  bank_name text,
  account_number text,
  account_holder text,
  -- 마스킹은 저장 시점에 만든다. 화면이 원문을 읽어 가공하면 원문이 앱 메모리와
  -- 로그를 거치게 된다. 파기 후에도 이 값은 남아 "무엇을 받았었는지"를 말한다.
  masked_account text not null,
  masked_holder text not null,
  created_at timestamptz not null default now(),
  purge_after timestamptz,
  purged_at timestamptz,
  constraint claim_refund_accounts_bank_name_check check (
    bank_name is null
    or (btrim(bank_name) = bank_name and length(bank_name) between 1 and 40)
  ),
  constraint claim_refund_accounts_account_number_check check (
    account_number is null
    or account_number ~ '^[0-9-]{8,30}$'
  ),
  constraint claim_refund_accounts_account_holder_check check (
    account_holder is null
    or (btrim(account_holder) = account_holder and length(account_holder) between 1 and 40)
  ),
  -- 파기된 행은 원문 세 칸이 모두 비어야 한다. 하나라도 남으면 파기가 아니다.
  constraint claim_refund_accounts_purge_complete_check check (
    purged_at is null
    or (bank_name is null and account_number is null and account_holder is null)
  )
);

create index claim_refund_accounts_purge_idx
  on private.claim_refund_accounts (purge_after)
  where purged_at is null and purge_after is not null;

alter table private.claim_refund_accounts enable row level security;
revoke all on table private.claim_refund_accounts
  from public, anon, authenticated, service_role;
grant select, insert, update on table private.claim_refund_accounts to service_role;

-- ---------------------------------------------------------------------------
-- 4. refunds 원장 확장 — 수단·처리자·시각·상계
-- ---------------------------------------------------------------------------
-- refunds에는 unique(payment_id)가 있다(#92). 결제 1건당 환불 1건·전액이라는
-- 뜻이고, v1이 주문 단위 전액이므로 충돌은 없다. 부분 환불을 여기서 시도하면
-- 그 인덱스부터 지워야 하고 재고 복원 계약이 통째로 무너진다.
alter table public.refunds
  add column method text,
  add column handled_by uuid references public.profiles(id) on delete set null,
  add column filed_at timestamptz,
  add column completed_at timestamptz,
  add column settlement_note text;

alter table public.refunds
  add constraint refunds_method_check
  check (method is null or method in ('pg_cancel', 'bank_transfer'));

alter table public.refunds
  add constraint refunds_settlement_note_check
  check (
    settlement_note is null
    or (btrim(settlement_note) = settlement_note and length(settlement_note) between 1 and 300)
  );

-- 새 컬럼은 구매자 컬럼 grant에 넣지 않는다. 처리자와 상계 메모는 운영 정보다.
-- 다만 수단은 "카드 취소로 돌려받는지 계좌로 받는지"라 구매자에게 필요하다.
grant select (method) on table public.refunds to authenticated;

-- ---------------------------------------------------------------------------
-- 5. 클레임 접수 (사용자)
-- ---------------------------------------------------------------------------
create or replace function public.request_order_claim(
  p_order_id uuid,
  p_user_id uuid,
  p_claim_type text,
  p_reason text,
  p_reason_type text,
  p_bank_name text default null,
  p_account_number text default null,
  p_account_holder text default null
)
returns text
language plpgsql
volatile
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid;
  v_status public.order_status;
  v_delivered_at timestamptz;
  v_claim_id uuid;
  v_has_unresolved_attempt boolean;
  v_masked_account text;
  v_masked_holder text;
  v_payment_count integer;
begin
  if p_claim_type is null or p_claim_type not in ('cancel', 'return', 'exchange') then
    raise check_violation using message = 'invalid claim type';
  end if;
  if p_reason_type is null or p_reason_type not in ('change_of_mind', 'defect') then
    raise check_violation using message = 'invalid cancellation reason type';
  end if;
  if p_reason is null
    or btrim(p_reason) <> p_reason
    or length(p_reason) not between 1 and 200
  then
    raise check_violation using message = 'invalid cancellation reason';
  end if;

  -- 잠금 순서는 기존 계약과 같다: 주문 → 결제 시도 → 결제.
  select orders.user_id, orders.status, orders.delivered_at
  into v_user_id, v_status, v_delivered_at
  from public.orders
  where orders.id = p_order_id
  for update;

  if not found or p_user_id is null or v_user_id is distinct from p_user_id then
    return 'not_found';
  end if;

  perform attempt.id
  from public.payment_attempts as attempt
  where attempt.purpose = 'order'
    and attempt.ref_id = p_order_id
  order by attempt.id
  for update;

  select exists (
    select 1
    from public.payment_attempts as attempt
    where attempt.purpose = 'order'
      and attempt.ref_id = p_order_id
      and attempt.state in (
        'prepared', 'confirming', 'unknown', 'needs_review', 'approved'
      )
  )
  into v_has_unresolved_attempt;

  if v_status = 'canceled' then
    return 'already_canceled';
  end if;

  -- 반품·교환은 물리적 회수를 전제한다. 배송이 끝나기 전에는 회수할 물건이
  -- 고객에게 없으므로 취소로 받는다.
  if p_claim_type in ('return', 'exchange') then
    if v_status not in ('delivered', 'done') then
      return 'not_claimable';
    end if;
  elsif v_status not in ('pending', 'paid', 'confirmed', 'shipping', 'delivered', 'done') then
    return 'not_cancelable';
  end if;

  -- 교환도 청약철회 기한을 준용한다(변심 7일 · 하자 3개월). 판정의 진실원은
  -- 계속 order_withdrawal_deadline_passed 하나다.
  if public.order_withdrawal_deadline_passed(v_delivered_at, p_reason_type, now()) then
    return 'deadline_expired';
  end if;

  if exists (
    select 1
    from public.order_cancellation_requests as request
    where request.order_id = p_order_id
      and request.status in ('requested', 'processing', 'needs_review')
  ) then
    return 'already_requested';
  end if;

  insert into public.order_cancellation_requests (
    order_id,
    requested_by,
    reason,
    reason_type,
    claim_type,
    status,
    stage
  )
  values (
    p_order_id,
    p_user_id,
    p_reason,
    p_reason_type,
    p_claim_type,
    'requested',
    'requested'
  )
  returning id into v_claim_id;

  -- 환불계좌는 무통장 환불의 유일한 경로이고 카드 fallback의 안전망이다.
  -- 세 칸이 모두 있을 때만 저장한다 — 반쪽 계좌는 송금에 쓸 수 없다.
  if p_bank_name is not null
    and p_account_number is not null
    and p_account_holder is not null
  then
    v_masked_account := public.mask_refund_account_number(p_account_number);
    v_masked_holder := public.mask_refund_account_holder(p_account_holder);

    insert into private.claim_refund_accounts (
      claim_id,
      bank_name,
      account_number,
      account_holder,
      masked_account,
      masked_holder
    )
    values (
      v_claim_id,
      btrim(p_bank_name),
      p_account_number,
      btrim(p_account_holder),
      btrim(p_bank_name) || ' ' || v_masked_account,
      v_masked_holder
    );
  end if;

  -- 결제 이력이 없는 pending 주문은 예전처럼 즉시 종결한다.
  if p_claim_type = 'cancel'
    and v_status = 'pending'
    and not v_has_unresolved_attempt
    and not exists (
      select 1
      from public.payments as payment
      where payment.purpose = 'order'
        and payment.ref_id = p_order_id
    )
  then
    perform public.finalize_order_cancellation_with_provider_evidence(
      p_order_id,
      p_reason,
      array[]::text[]
    );

    update public.order_cancellation_requests
    set
      status = 'completed',
      stage = 'completed',
      completed_at = now(),
      updated_at = now()
    where id = v_claim_id;

    return 'completed';
  end if;

  /*
   * 자동 승인 — paid(발주확인 전) 변심 취소.
   *
   * 아직 발주확인도 하지 않은 주문의 변심 취소를 사람이 판단할 이유가 없다.
   * 스마트스토어와 같은 경계다. confirmed부터는 발송 준비가 시작됐으므로
   * 운영자 판단으로 남긴다.
   *
   * 승인의 실질(durable claim + 환불 intent)은 admin_decide_order_cancellation의
   * 승인 분기와 같다. decided_by는 null로 남긴다 — 사람이 누른 적이 없다.
   */
  if p_claim_type = 'cancel'
    and v_status = 'paid'
    and p_reason_type = 'change_of_mind'
  then
    insert into public.order_cancellation_claims (
      order_id,
      requested_by,
      previous_status
    )
    values (p_order_id, p_user_id, v_status)
    on conflict (order_id) do nothing;

    insert into public.refunds (
      payment_id,
      amount,
      reason,
      status,
      cancellation_request_id
    )
    select
      payment.id,
      payment.amount,
      p_reason,
      case when refund.status = 'done' then 'done' else 'requested' end,
      v_claim_id
    from public.payments as payment
    left join public.refunds as refund on refund.payment_id = payment.id
    where payment.purpose = 'order'
      and payment.ref_id = p_order_id
      and payment.status in ('pending', 'paid', 'canceled', 'refunded')
    on conflict (payment_id) do update
    set
      cancellation_request_id = excluded.cancellation_request_id,
      reason = coalesce(public.refunds.reason, excluded.reason),
      status = case
        when public.refunds.status = 'done' then 'done'
        else 'requested'
      end;

    select count(*)::integer
    into v_payment_count
    from public.payments as payment
    where payment.purpose = 'order'
      and payment.ref_id = p_order_id
      and payment.status in ('pending', 'paid', 'canceled', 'refunded');

    update public.order_cancellation_requests
    set
      status = 'processing',
      stage = 'processing',
      decided_at = now(),
      provider_started_at = now(),
      updated_at = now()
    where id = v_claim_id;

    insert into public.audit_log (actor_id, action, target, diff)
    values (
      p_user_id,
      'order.claim_auto_approved',
      'order:' || p_order_id::text,
      jsonb_build_object(
        'claimId', v_claim_id,
        'claimType', 'cancel',
        'from', 'requested',
        'to', 'processing',
        'previousOrderStatus', v_status::text,
        'reasonType', p_reason_type,
        'paymentCount', v_payment_count
      )
    );

    perform private.notify_order_claim(
      v_claim_id,
      '취소 요청이 접수됐어요',
      '발송 전 주문이라 자동으로 승인됐습니다. 결제 취소 처리를 시작합니다.'
    );

    return 'auto_approved';
  end if;

  perform private.notify_order_claim(
    v_claim_id,
    '클레임 요청이 접수됐어요',
    '요청을 접수했습니다. 담당자가 확인한 뒤 진행 상황을 알려드립니다.'
  );

  return 'requested';
end;
$$;

revoke all on function public.request_order_claim(
  uuid, uuid, text, text, text, text, text, text
) from public, anon, authenticated, service_role;
grant execute on function public.request_order_claim(
  uuid, uuid, text, text, text, text, text, text
) to service_role;

-- 기존 4-arg 진입점은 취소 클레임의 별칭으로 남긴다. /api/orders/[id]/cancel과
-- 그 테스트가 계속 이 시그니처를 부른다.
create or replace function public.request_order_cancellation(
  p_order_id uuid,
  p_user_id uuid,
  p_reason text,
  p_reason_type text
)
returns text
language plpgsql
volatile
security definer
set search_path = public, pg_temp
as $$
declare
  v_result text;
begin
  v_result := public.request_order_claim(
    p_order_id,
    p_user_id,
    'cancel',
    p_reason,
    p_reason_type
  );

  -- 자동 승인은 호출자에게 "접수됨"이다. 기존 응답 계약(requested/completed/…)을
  -- 넓히면 이미 배포된 라우트가 모르는 값을 502로 바꾼다.
  return case when v_result = 'auto_approved' then 'requested' else v_result end;
end;
$$;

revoke all on function public.request_order_cancellation(uuid, uuid, text, text)
  from public, anon, authenticated, service_role;
grant execute on function public.request_order_cancellation(uuid, uuid, text, text)
  to service_role;

-- ---------------------------------------------------------------------------
-- 6. 마스킹과 알림 헬퍼
-- ---------------------------------------------------------------------------
-- 계좌번호는 뒤 4자리만 남긴다. 앞자리를 남기면 은행 코드와 지점이 드러난다.
create or replace function public.mask_refund_account_number(p_value text)
returns text
language sql
immutable
set search_path = ''
as $$
  select case
    when p_value is null then null
    when pg_catalog.length(pg_catalog.replace(p_value, '-', '')) <= 4
      then pg_catalog.repeat('*', 4)
    else pg_catalog.repeat('*', pg_catalog.length(pg_catalog.replace(p_value, '-', '')) - 4)
      || pg_catalog.right(pg_catalog.replace(p_value, '-', ''), 4)
  end;
$$;

create or replace function public.mask_refund_account_holder(p_value text)
returns text
language sql
immutable
set search_path = ''
as $$
  select case
    when p_value is null then null
    when pg_catalog.length(pg_catalog.btrim(p_value)) <= 1
      then pg_catalog.btrim(p_value)
    else pg_catalog.left(pg_catalog.btrim(p_value), 1)
      || pg_catalog.repeat('*', pg_catalog.length(pg_catalog.btrim(p_value)) - 1)
  end;
$$;

revoke all on function public.mask_refund_account_number(text)
  from public, anon, authenticated, service_role;
grant execute on function public.mask_refund_account_number(text) to service_role;

revoke all on function public.mask_refund_account_holder(text)
  from public, anon, authenticated, service_role;
grant execute on function public.mask_refund_account_holder(text) to service_role;

/*
 * 클레임 상태 변화 알림.
 *
 * dedupe_key에 stage를 넣어 같은 단계를 두 번 알리지 않는다. 상태가 실제로
 * 바뀔 때만 새 행이 생긴다.
 */
create or replace function private.notify_order_claim(
  p_claim_id uuid,
  p_title text,
  p_body text
)
returns void
language plpgsql
volatile
security definer
set search_path = ''
as $function$
declare
  v_claim public.order_cancellation_requests%rowtype;
begin
  select request.*
  into v_claim
  from public.order_cancellation_requests as request
  where request.id = p_claim_id;

  if not found then
    return;
  end if;

  insert into public.notifications (
    user_id,
    type,
    title,
    body,
    link_path,
    source_type,
    source_id,
    dedupe_key
  )
  values (
    v_claim.requested_by,
    'claim_updated',
    p_title,
    p_body,
    '/orders/' || v_claim.order_id::text,
    'order_claim',
    v_claim.id::text,
    'claim:' || v_claim.stage || ':' || v_claim.id::text
  )
  on conflict (user_id, dedupe_key) do nothing;
end;
$function$;

revoke all on function private.notify_order_claim(uuid, text, text)
  from public, anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 7. 운영자 결정 — 승인·거부·보류·재개
-- ---------------------------------------------------------------------------
create or replace function public.admin_decide_order_claim(
  p_claim_id uuid,
  p_decision text,
  p_note text
)
returns text
language plpgsql
volatile
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor uuid := (select auth.uid());
  v_order_id uuid;
  v_order_status public.order_status;
  v_delivered_at timestamptz;
  v_claim record;
  v_next_stage text;
  v_next_status text;
  v_payment_count integer;
begin
  if v_actor is null or not public.is_staff() then
    raise insufficient_privilege using message = 'staff required';
  end if;

  if p_decision not in ('review', 'approve', 'reject', 'hold', 'resume') then
    raise check_violation using message = 'invalid claim decision';
  end if;

  select request.order_id
  into v_order_id
  from public.order_cancellation_requests as request
  where request.id = p_claim_id;

  if v_order_id is null then
    raise no_data_found using message = 'claim_not_found';
  end if;

  -- 잠금 순서: 주문 → 클레임. admin_decide_order_cancellation과 같다.
  select orders.status, orders.delivered_at
  into v_order_status, v_delivered_at
  from public.orders
  where orders.id = v_order_id
  for update;

  select request.*
  into v_claim
  from public.order_cancellation_requests as request
  where request.id = p_claim_id
  for update;

  if v_claim.stage in ('completed', 'rejected') then
    raise exception using message = 'claim_not_decidable';
  end if;

  if p_decision = 'reject' then
    if p_note is null
      or btrim(p_note) <> p_note
      or length(p_note) not between 10 and 200
    then
      raise check_violation using message = 'invalid rejection reason';
    end if;

    update public.order_cancellation_requests
    set
      status = 'rejected',
      stage = 'rejected',
      decided_by = v_actor,
      decision_note = p_note,
      decided_at = now(),
      updated_at = now()
    where id = p_claim_id;

    insert into public.audit_log (actor_id, action, target, diff)
    values (
      v_actor,
      'admin.order.claim_rejected',
      'order:' || v_order_id::text,
      jsonb_build_object(
        'claimId', p_claim_id,
        'claimType', v_claim.claim_type,
        'from', v_claim.stage,
        'to', 'rejected',
        'reason', p_note
      )
    );

    perform private.notify_order_claim(
      p_claim_id,
      '클레임 요청이 거절됐어요',
      '요청이 거절됐습니다. 사유: ' || p_note
    );
    return 'rejected';
  end if;

  if p_decision = 'hold' then
    if p_note is null
      or btrim(p_note) <> p_note
      or length(p_note) not between 10 and 200
    then
      raise check_violation using message = 'invalid hold reason';
    end if;
    if v_claim.stage = 'on_hold' then
      return 'on_hold';
    end if;

    update public.order_cancellation_requests
    set
      status = 'requested',
      stage = 'on_hold',
      held_from = v_claim.stage,
      hold_reason = p_note,
      held_at = now(),
      updated_at = now()
    where id = p_claim_id;

    insert into public.audit_log (actor_id, action, target, diff)
    values (
      v_actor,
      'admin.order.claim_held',
      'order:' || v_order_id::text,
      jsonb_build_object(
        'claimId', p_claim_id,
        'claimType', v_claim.claim_type,
        'from', v_claim.stage,
        'to', 'on_hold',
        'reason', p_note
      )
    );

    perform private.notify_order_claim(
      p_claim_id,
      '클레임 처리가 보류됐어요',
      '처리가 보류됐습니다. 사유: ' || p_note
    );
    return 'on_hold';
  end if;

  if p_decision = 'resume' then
    if v_claim.stage <> 'on_hold' then
      raise exception using message = 'claim_not_held';
    end if;

    v_next_stage := coalesce(v_claim.held_from, 'requested');

    update public.order_cancellation_requests
    set
      status = case when v_next_stage = 'processing' then 'processing' else 'requested' end,
      stage = v_next_stage,
      held_from = null,
      hold_reason = null,
      held_at = null,
      updated_at = now()
    where id = p_claim_id;

    insert into public.audit_log (actor_id, action, target, diff)
    values (
      v_actor,
      'admin.order.claim_resumed',
      'order:' || v_order_id::text,
      jsonb_build_object(
        'claimId', p_claim_id,
        'claimType', v_claim.claim_type,
        'from', 'on_hold',
        'to', v_next_stage
      )
    );

    perform private.notify_order_claim(
      p_claim_id,
      '클레임 처리가 재개됐어요',
      '보류가 해제되어 처리가 다시 시작됐습니다.'
    );
    return v_next_stage;
  end if;

  if p_decision = 'review' then
    if v_claim.stage <> 'requested' then
      raise exception using message = 'claim_not_decidable';
    end if;

    update public.order_cancellation_requests
    set
      status = 'requested',
      stage = 'in_review',
      decided_by = v_actor,
      updated_at = now()
    where id = p_claim_id;

    insert into public.audit_log (actor_id, action, target, diff)
    values (
      v_actor,
      'admin.order.claim_in_review',
      'order:' || v_order_id::text,
      jsonb_build_object(
        'claimId', p_claim_id,
        'claimType', v_claim.claim_type,
        'from', 'requested',
        'to', 'in_review'
      )
    );
    return 'in_review';
  end if;

  -- 승인.
  if v_claim.stage not in ('requested', 'in_review') then
    raise exception using message = 'claim_not_decidable';
  end if;

  if v_order_status not in (
    'pending', 'paid', 'confirmed', 'shipping', 'delivered', 'done'
  ) then
    raise exception using message = 'order_not_cancelable';
  end if;

  -- 돈이 걸린 판정은 승인 단계에서 다시 본다(#189). 기준 시각은 접수 시각이다.
  if public.order_withdrawal_deadline_passed(
    v_delivered_at,
    v_claim.reason_type,
    v_claim.requested_at
  ) then
    raise check_violation using message = 'withdrawal_deadline_expired';
  end if;

  -- 취소는 회수할 물건이 없으므로 곧장 환불 처리로 간다. 반품·교환은 수거부터다.
  if v_claim.claim_type = 'cancel' then
    v_next_stage := 'processing';
    v_next_status := 'processing';
  else
    v_next_stage := 'collecting';
    v_next_status := 'requested';
  end if;

  if v_next_stage = 'processing' then
    insert into public.order_cancellation_claims (
      order_id,
      requested_by,
      previous_status
    )
    values (v_order_id, v_claim.requested_by, v_order_status)
    on conflict (order_id) do nothing;

    insert into public.refunds (
      payment_id,
      amount,
      reason,
      status,
      cancellation_request_id
    )
    select
      payment.id,
      payment.amount,
      v_claim.reason,
      case when refund.status = 'done' then 'done' else 'requested' end,
      p_claim_id
    from public.payments as payment
    left join public.refunds as refund on refund.payment_id = payment.id
    where payment.purpose = 'order'
      and payment.ref_id = v_order_id
      and payment.status in ('pending', 'paid', 'canceled', 'refunded')
    on conflict (payment_id) do update
    set
      cancellation_request_id = excluded.cancellation_request_id,
      reason = coalesce(public.refunds.reason, excluded.reason),
      status = case
        when public.refunds.status = 'done' then 'done'
        else 'requested'
      end;

    select count(*)::integer
    into v_payment_count
    from public.payments as payment
    where payment.purpose = 'order'
      and payment.ref_id = v_order_id
      and payment.status in ('pending', 'paid', 'canceled', 'refunded');
  end if;

  update public.order_cancellation_requests
  set
    status = v_next_status,
    stage = v_next_stage,
    decided_by = v_actor,
    decision_note = null,
    decided_at = now(),
    provider_started_at = case when v_next_stage = 'processing' then now() else provider_started_at end,
    collecting_at = case when v_next_stage = 'collecting' then now() else collecting_at end,
    updated_at = now()
  where id = p_claim_id;

  insert into public.audit_log (actor_id, action, target, diff)
  values (
    v_actor,
    'admin.order.claim_approved',
    'order:' || v_order_id::text,
    jsonb_build_object(
      'claimId', p_claim_id,
      'claimType', v_claim.claim_type,
      'from', v_claim.stage,
      'to', v_next_stage,
      'previousOrderStatus', v_order_status::text,
      'reasonType', v_claim.reason_type,
      'paymentCount', coalesce(v_payment_count, 0)
    )
  );

  perform private.notify_order_claim(
    p_claim_id,
    '클레임 요청이 승인됐어요',
    case
      when v_next_stage = 'collecting'
        then '요청이 승인됐습니다. 안내받은 방법으로 굿즈를 반송해주세요.'
      else '요청이 승인됐습니다. 결제 취소 처리를 시작합니다.'
    end
  );

  return v_next_stage;
end;
$$;

revoke all on function public.admin_decide_order_claim(uuid, text, text)
  from public, anon, authenticated, service_role;
grant execute on function public.admin_decide_order_claim(uuid, text, text)
  to authenticated;

-- ---------------------------------------------------------------------------
-- 8. 수거·입고 확인
-- ---------------------------------------------------------------------------
-- D11("입고 확인은 승인에 내포")을 명시 상태로 승격한다. 반품·교환에서
-- "물건이 창고에 도착했는가"는 환불·재출고를 여는 사실이고, 승인 버튼 하나에
-- 접혀 있으면 그 사실이 어디에도 기록되지 않는다.
create or replace function public.admin_record_order_claim_collection(
  p_claim_id uuid,
  p_stage text
)
returns text
language plpgsql
volatile
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor uuid := (select auth.uid());
  v_claim record;
begin
  if v_actor is null or not public.is_staff() then
    raise insufficient_privilege using message = 'staff required';
  end if;

  if p_stage not in ('collecting', 'collected') then
    raise check_violation using message = 'invalid collection stage';
  end if;

  select request.*
  into v_claim
  from public.order_cancellation_requests as request
  where request.id = p_claim_id
  for update;

  if not found then
    raise no_data_found using message = 'claim_not_found';
  end if;

  if v_claim.claim_type = 'cancel' then
    raise exception using message = 'claim_type_has_no_collection';
  end if;

  -- 수거 시작은 승인이 이미 만든다. 같은 값으로 다시 부르면 멱등하게 통과하고,
  -- 그 밖의 단계에서 부르면 거절한다 — 뒤로 감는 전이를 만들지 않는다.
  if p_stage = 'collecting' then
    if v_claim.stage = 'collecting' then
      return 'collecting';
    end if;
    raise exception using message = 'claim_not_collectable';
  end if;

  if v_claim.stage = 'collected' then
    return 'collected';
  end if;
  if v_claim.stage <> 'collecting' then
    raise exception using message = 'claim_not_collectable';
  end if;

  update public.order_cancellation_requests
  set
    status = 'requested',
    stage = p_stage,
    collected_at = case when p_stage = 'collected' then now() else collected_at end,
    updated_at = now()
  where id = p_claim_id;

  insert into public.audit_log (actor_id, action, target, diff)
  values (
    v_actor,
    'admin.order.claim_collected',
    'order:' || v_claim.order_id::text,
    jsonb_build_object(
      'claimId', p_claim_id,
      'claimType', v_claim.claim_type,
      'from', v_claim.stage,
      'to', p_stage
    )
  );

  perform private.notify_order_claim(
    p_claim_id,
    '반송한 굿즈가 입고됐어요',
    case
      when v_claim.claim_type = 'exchange'
        then '입고가 확인됐습니다. 교환 상품 재출고를 준비합니다.'
      else '입고가 확인됐습니다. 영업일 기준 3일 이내에 환급 절차를 진행합니다.'
    end
  );

  return p_stage;
end;
$$;

revoke all on function public.admin_record_order_claim_collection(uuid, text)
  from public, anon, authenticated, service_role;
grant execute on function public.admin_record_order_claim_collection(uuid, text)
  to authenticated;

-- ---------------------------------------------------------------------------
-- 9. 환불 원장 — 접수와 완료
-- ---------------------------------------------------------------------------
/*
 * 이 함수는 돈을 움직이지 않는다. 원장에 "어떤 수단으로 누가 언제 접수했는가"를
 * 적을 뿐이다.
 *
 * `filed`(접수): 반품은 입고 확인(collected) 뒤에만, 취소는 승인 뒤(processing)에
 *   부를 수 있다. 반품의 경우 여기서 durable claim과 환불 intent가 생긴다 —
 *   D11이 말한 "물건을 받은 뒤 승인한다"가 실제로 일어나는 지점이다.
 *
 * `completed`(완료): 클레임이 이미 completed일 때만 허용한다. completed는
 *   finalize_order_cancellation_with_provider_evidence를 지난 경로(legacy Toss
 *   오케스트레이터 · Korpay finalize_goods_manual_payment_recovery)만 만들 수
 *   있으므로, 재고 복원과 카드팩 회수 없이 "환불 완료"가 기록되는 조합이
 *   DB에서 불가능해진다.
 */
create or replace function public.admin_record_order_claim_refund(
  p_claim_id uuid,
  p_method text,
  p_stage text,
  p_note text default null
)
returns text
language plpgsql
volatile
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor uuid := (select auth.uid());
  v_claim record;
  v_order_status public.order_status;
  v_refund_count integer;
begin
  if v_actor is null or not public.is_staff() then
    raise insufficient_privilege using message = 'staff required';
  end if;

  if p_method not in ('pg_cancel', 'bank_transfer') then
    raise check_violation using message = 'invalid refund method';
  end if;
  if p_stage not in ('filed', 'completed') then
    raise check_violation using message = 'invalid refund stage';
  end if;
  if p_note is not null
    and (btrim(p_note) <> p_note or length(p_note) not between 1 and 300)
  then
    raise check_violation using message = 'invalid settlement note';
  end if;

  select request.order_id
  into v_claim
  from public.order_cancellation_requests as request
  where request.id = p_claim_id;

  if not found then
    raise no_data_found using message = 'claim_not_found';
  end if;

  select orders.status
  into v_order_status
  from public.orders
  where orders.id = v_claim.order_id
  for update;

  select request.*
  into v_claim
  from public.order_cancellation_requests as request
  where request.id = p_claim_id
  for update;

  if v_claim.claim_type = 'exchange' then
    raise exception using message = 'exchange_has_no_refund';
  end if;

  perform payment.id
  from public.payments as payment
  where payment.purpose = 'order'
    and payment.ref_id = v_claim.order_id
  order by payment.id
  for update;

  if p_stage = 'filed' then
    if v_claim.stage not in ('collected', 'processing') then
      raise exception using message = 'claim_not_refundable';
    end if;

    -- 반품은 입고가 확인된 뒤에야 durable claim이 생긴다. 그 전에 만들면
    -- 물건이 돌아오지 않은 주문의 재고가 복원 대기 상태로 열린다.
    if v_claim.stage = 'collected' then
      insert into public.order_cancellation_claims (
        order_id,
        requested_by,
        previous_status
      )
      values (v_claim.order_id, v_claim.requested_by, v_order_status)
      on conflict (order_id) do nothing;

      insert into public.refunds (
        payment_id,
        amount,
        reason,
        status,
        cancellation_request_id
      )
      select
        payment.id,
        payment.amount,
        v_claim.reason,
        case when refund.status = 'done' then 'done' else 'requested' end,
        p_claim_id
      from public.payments as payment
      left join public.refunds as refund on refund.payment_id = payment.id
      where payment.purpose = 'order'
        and payment.ref_id = v_claim.order_id
        and payment.status in ('pending', 'paid', 'canceled', 'refunded')
      on conflict (payment_id) do update
      set
        cancellation_request_id = excluded.cancellation_request_id,
        reason = coalesce(public.refunds.reason, excluded.reason),
        status = case
          when public.refunds.status = 'done' then 'done'
          else 'requested'
        end;

      update public.order_cancellation_requests
      set
        status = 'processing',
        stage = 'processing',
        provider_started_at = coalesce(provider_started_at, now()),
        updated_at = now()
      where id = p_claim_id;
    end if;

    update public.refunds as refund
    set
      method = p_method,
      handled_by = v_actor,
      filed_at = coalesce(refund.filed_at, now()),
      settlement_note = coalesce(p_note, refund.settlement_note)
    from public.payments as payment
    where refund.payment_id = payment.id
      and payment.purpose = 'order'
      and payment.ref_id = v_claim.order_id;

    insert into public.audit_log (actor_id, action, target, diff)
    values (
      v_actor,
      'admin.order.claim_refund_filed',
      'order:' || v_claim.order_id::text,
      jsonb_build_object(
        'claimId', p_claim_id,
        'claimType', v_claim.claim_type,
        'method', p_method,
        'from', v_claim.stage,
        'to', 'processing'
      )
    );

    perform private.notify_order_claim(
      p_claim_id,
      '환불 접수가 완료됐어요',
      case
        when p_method = 'bank_transfer'
          then '등록하신 환불계좌로 송금을 접수했습니다.'
        else '결제사에 결제 취소를 접수했습니다. 카드사 처리 일정에 따라 반영 시점이 다를 수 있습니다.'
      end
    );

    return 'filed';
  end if;

  -- 완료 기록.
  if v_claim.stage <> 'completed' then
    raise exception using message = 'claim_refund_finalization_required';
  end if;

  update public.refunds as refund
  set
    method = coalesce(refund.method, p_method),
    handled_by = coalesce(refund.handled_by, v_actor),
    completed_at = coalesce(refund.completed_at, now()),
    settlement_note = coalesce(p_note, refund.settlement_note)
  from public.payments as payment
  where refund.payment_id = payment.id
    and payment.purpose = 'order'
    and payment.ref_id = v_claim.order_id;

  get diagnostics v_refund_count = row_count;

  -- 환불 원장이 한 줄도 없는 완료는 "돈은 돌아갔는데 장부가 비었다"는 뜻이다.
  -- 첫 판매 리스크 목록이 지적한 그 상태를 여기서 막는다.
  if v_refund_count = 0 then
    raise exception using message = 'claim_refund_ledger_missing';
  end if;

  -- 환불계좌 원문은 완료 30일 뒤 파기한다(#208 안전 기본값).
  update private.claim_refund_accounts as account
  set purge_after = coalesce(account.purge_after, now() + interval '30 days')
  where account.claim_id = p_claim_id;

  insert into public.audit_log (actor_id, action, target, diff)
  values (
    v_actor,
    'admin.order.claim_refund_completed',
    'order:' || v_claim.order_id::text,
    jsonb_build_object(
      'claimId', p_claim_id,
      'claimType', v_claim.claim_type,
      'method', p_method,
      'refundRows', v_refund_count,
      'settlementNote', p_note
    )
  );

  perform private.notify_order_claim(
    p_claim_id,
    '환불이 완료됐어요',
    '환급 처리가 완료됐습니다. 결제수단에 따라 반영 시점이 다를 수 있습니다.'
  );

  return 'completed';
end;
$$;

revoke all on function public.admin_record_order_claim_refund(uuid, text, text, text)
  from public, anon, authenticated, service_role;
grant execute on function public.admin_record_order_claim_refund(uuid, text, text, text)
  to authenticated;

-- ---------------------------------------------------------------------------
-- 10. 교환 재출고
-- ---------------------------------------------------------------------------
-- 교환은 환불이 아니라 재출고로 종결한다. 재고 복원도 카드팩 회수도 하지 않는다 —
-- 같은 굿즈가 다시 나가므로 재고는 이미 맞고, 주문은 살아 있으므로 그 주문으로
-- 지급된 카드팩도 그대로 유효하다.
create or replace function public.admin_record_order_claim_reshipment(
  p_claim_id uuid,
  p_carrier text,
  p_tracking_number text
)
returns text
language plpgsql
volatile
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor uuid := (select auth.uid());
  v_claim record;
  v_carrier text := nullif(btrim(coalesce(p_carrier, '')), '');
  v_tracking text := nullif(btrim(coalesce(p_tracking_number, '')), '');
begin
  if v_actor is null or not public.is_staff() then
    raise insufficient_privilege using message = 'staff required';
  end if;

  if v_carrier is null or v_tracking is null then
    raise check_violation using message = 'invalid reshipment tracking';
  end if;
  if v_tracking !~ '^[A-Z0-9]{8,30}$' then
    raise check_violation using message = 'invalid reshipment tracking';
  end if;
  -- 비활성 택배사는 새로 고를 수 없다. 기존 주문의 조회 링크는 계속 살아 있다.
  if not exists (
    select 1
    from public.shipping_carriers as carrier
    where carrier.code = v_carrier
      and carrier.is_active
  ) then
    raise check_violation using message = 'unknown shipping carrier';
  end if;

  select request.*
  into v_claim
  from public.order_cancellation_requests as request
  where request.id = p_claim_id
  for update;

  if not found then
    raise no_data_found using message = 'claim_not_found';
  end if;

  if v_claim.claim_type <> 'exchange' then
    raise exception using message = 'claim_type_has_no_reshipment';
  end if;

  if v_claim.stage = 'completed' then
    return 'completed';
  end if;

  if v_claim.stage <> 'collected' then
    raise exception using message = 'claim_not_reshippable';
  end if;

  update public.order_cancellation_requests
  set
    status = 'completed',
    stage = 'completed',
    reship_carrier = v_carrier,
    reship_tracking_number = v_tracking,
    reshipped_at = now(),
    completed_at = now(),
    updated_at = now()
  where id = p_claim_id;

  insert into public.audit_log (actor_id, action, target, diff)
  values (
    v_actor,
    'admin.order.claim_reshipped',
    'order:' || v_claim.order_id::text,
    jsonb_build_object(
      'claimId', p_claim_id,
      'claimType', 'exchange',
      'from', 'collected',
      'to', 'completed',
      'carrier', v_carrier
    )
  );

  perform private.notify_order_claim(
    p_claim_id,
    '교환 상품이 재출고됐어요',
    '교환 상품을 새 운송장으로 발송했습니다.'
  );

  return 'completed';
end;
$$;

revoke all on function public.admin_record_order_claim_reshipment(uuid, text, text)
  from public, anon, authenticated, service_role;
grant execute on function public.admin_record_order_claim_reshipment(uuid, text, text)
  to authenticated;

-- ---------------------------------------------------------------------------
-- 11. 콘솔 조회
-- ---------------------------------------------------------------------------
create or replace function public.admin_search_order_claims(
  p_claim_type text default null,
  p_stage text default null,
  p_reason_type text default null,
  p_from date default null,
  p_to date default null,
  p_query text default null,
  p_limit integer default 20,
  p_offset integer default 0
)
returns table (
  id uuid,
  reference bigint,
  order_id uuid,
  claim_type text,
  stage text,
  reason_type text,
  buyer_name text,
  buyer_email text,
  order_status public.order_status,
  order_total bigint,
  requested_at timestamptz,
  collected_at timestamptz,
  completed_at timestamptz,
  refund_method text,
  handler_name text,
  total_count bigint
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_query text := nullif(btrim(coalesce(p_query, '')), '');
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 100);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_stages text[];
begin
  if (select auth.uid()) is null or not public.is_staff() then
    raise insufficient_privilege using message = 'staff required';
  end if;

  if p_claim_type is not null and p_claim_type not in ('cancel', 'return', 'exchange') then
    raise check_violation using message = 'invalid claim type filter';
  end if;
  if p_from is not null and p_to is not null and p_from > p_to then
    raise check_violation using message = 'invalid claim date range';
  end if;
  if v_query is not null and length(v_query) > 100 then
    raise check_violation using message = 'claim search query too long';
  end if;

  -- 'open'은 단계 하나가 아니라 "아직 끝나지 않은 것 전부"다. 화면이 이 집합을
  -- 직접 나열하면 단계를 하나 더할 때 목록에서만 조용히 빠진다.
  if p_stage = 'open' then
    v_stages := array[
      'requested', 'in_review', 'collecting', 'collected',
      'on_hold', 'processing', 'needs_review'
    ];
  elsif p_stage is not null then
    v_stages := array[p_stage];
  end if;

  return query
  select
    request.id,
    request.reference,
    request.order_id,
    request.claim_type,
    request.stage,
    request.reason_type,
    profile.nickname as buyer_name,
    profile.email as buyer_email,
    orders.status as order_status,
    orders.total as order_total,
    request.requested_at,
    request.collected_at,
    request.completed_at,
    refund.method as refund_method,
    handler.nickname as handler_name,
    count(*) over()::bigint as total_count
  from public.order_cancellation_requests as request
  join public.orders as orders on orders.id = request.order_id
  join public.profiles as profile on profile.id = orders.user_id
  left join public.profiles as handler on handler.id = request.decided_by
  left join lateral (
    select payment_refund.method
    from public.refunds as payment_refund
    join public.payments as payment on payment.id = payment_refund.payment_id
    where payment.purpose = 'order'
      and payment.ref_id = request.order_id
    order by payment_refund.created_at desc, payment_refund.id desc
    limit 1
  ) as refund on true
  where (p_claim_type is null or request.claim_type = p_claim_type)
    and (v_stages is null or request.stage = any(v_stages))
    and (p_reason_type is null or request.reason_type = p_reason_type)
    and (
      p_from is null
      or request.requested_at >= (p_from::timestamp at time zone 'Asia/Seoul')
    )
    and (
      p_to is null
      or request.requested_at < ((p_to + 1)::timestamp at time zone 'Asia/Seoul')
    )
    and (
      v_query is null
      or position(lower(v_query) in lower(request.order_id::text)) > 0
      or position(lower(v_query) in lower(request.reference::text)) > 0
      or position(lower(v_query) in lower(coalesce(profile.email, ''))) > 0
      or position(lower(v_query) in lower(coalesce(profile.nickname, ''))) > 0
    )
  order by request.requested_at desc, request.id desc
  limit v_limit
  offset v_offset;
end;
$$;

revoke all on function public.admin_search_order_claims(
  text, text, text, date, date, text, integer, integer
) from public, anon, authenticated, service_role;
grant execute on function public.admin_search_order_claims(
  text, text, text, date, date, text, integer, integer
) to authenticated;

-- 0건 단계도 행으로 돌려준다. 화면이 "정말 0건"과 "집계 실패"를 구분해야 한다.
create or replace function public.admin_order_claim_stage_counts(
  p_claim_type text default null
)
returns table (stage text, total bigint)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if (select auth.uid()) is null or not public.is_staff() then
    raise insufficient_privilege using message = 'staff required';
  end if;

  if p_claim_type is not null and p_claim_type not in ('cancel', 'return', 'exchange') then
    raise check_violation using message = 'invalid claim type filter';
  end if;

  return query
  select
    known.value,
    count(request.id)::bigint
  from unnest(array[
    'requested', 'in_review', 'collecting', 'collected',
    'on_hold', 'processing', 'needs_review', 'completed', 'rejected'
  ]) as known(value)
  left join public.order_cancellation_requests as request
    on request.stage = known.value
   and (p_claim_type is null or request.claim_type = p_claim_type)
  group by known.value;
end;
$$;

revoke all on function public.admin_order_claim_stage_counts(text)
  from public, anon, authenticated, service_role;
grant execute on function public.admin_order_claim_stage_counts(text)
  to authenticated;

/*
 * 상세 컨텍스트 한 번의 왕복.
 *
 * 환불계좌는 마스킹 값만 나간다. 원문 컬럼은 private 테이블에 있고 이 함수는
 * masked_* 두 칸만 읽는다 — 실수로 select *를 적어도 원문이 결과에 실리지 않도록
 * 컬럼을 명시한다.
 */
create or replace function public.admin_order_claim_detail(p_claim_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor uuid := (select auth.uid());
  v_claim record;
  v_result jsonb;
begin
  if v_actor is null or not public.is_staff() then
    raise insufficient_privilege using message = 'staff required';
  end if;

  select request.*
  into v_claim
  from public.order_cancellation_requests as request
  where request.id = p_claim_id;

  if not found then
    return null;
  end if;

  select jsonb_build_object(
    'claim', jsonb_build_object(
      'id', v_claim.id,
      'reference', v_claim.reference,
      'orderId', v_claim.order_id,
      'claimType', v_claim.claim_type,
      'stage', v_claim.stage,
      'status', v_claim.status,
      'reason', v_claim.reason,
      'reasonType', v_claim.reason_type,
      'decisionNote', v_claim.decision_note,
      'holdReason', v_claim.hold_reason,
      'heldAt', v_claim.held_at,
      'requestedAt', v_claim.requested_at,
      'decidedAt', v_claim.decided_at,
      'collectingAt', v_claim.collecting_at,
      'collectedAt', v_claim.collected_at,
      'completedAt', v_claim.completed_at,
      'reshipCarrier', v_claim.reship_carrier,
      'reshipTrackingNumber', v_claim.reship_tracking_number,
      'reshippedAt', v_claim.reshipped_at,
      'lastErrorCode', v_claim.last_error_code,
      'handlerName', (
        select handler.nickname
        from public.profiles as handler
        where handler.id = v_claim.decided_by
      )
    ),
    'order', (
      select jsonb_build_object(
        'id', orders.id,
        'status', orders.status,
        'total', orders.total,
        'shippingFee', orders.shipping_fee,
        'createdAt', orders.created_at,
        'deliveredAt', orders.delivered_at,
        'shippingCarrier', orders.shipping_carrier,
        'trackingNumber', orders.tracking_number,
        'buyerName', profile.nickname,
        'buyerEmail', profile.email,
        'items', coalesce((
          select jsonb_agg(jsonb_build_object(
            'name', item.good_name_snapshot,
            'qty', item.qty,
            'unitPrice', item.unit_price
          ) order by item.id)
          from public.order_items as item
          where item.order_id = orders.id
        ), '[]'::jsonb)
      )
      from public.orders as orders
      join public.profiles as profile on profile.id = orders.user_id
      where orders.id = v_claim.order_id
    ),
    'payment', (
      select jsonb_build_object(
        'id', payment.id,
        'provider', payment.provider,
        'status', payment.status,
        'amount', payment.amount,
        'createdAt', payment.created_at
      )
      from public.payments as payment
      where payment.purpose = 'order'
        and payment.ref_id = v_claim.order_id
        and payment.status <> 'failed'
      order by payment.created_at desc, payment.id desc
      limit 1
    ),
    'refund', (
      select jsonb_build_object(
        'status', refund.status,
        'amount', refund.amount,
        'method', refund.method,
        'filedAt', refund.filed_at,
        'completedAt', refund.completed_at,
        'settlementNote', refund.settlement_note,
        'handlerName', (
          select handler.nickname
          from public.profiles as handler
          where handler.id = refund.handled_by
        )
      )
      from public.refunds as refund
      join public.payments as payment on payment.id = refund.payment_id
      where payment.purpose = 'order'
        and payment.ref_id = v_claim.order_id
      order by refund.created_at desc, refund.id desc
      limit 1
    ),
    -- 뽑기권 발급/사용 여부. 취소·반품 완료 시 회수 대상이 남아 있는지를
    -- 운영자가 승인 전에 봐야 한다(약관 제17조).
    'cardPacks', (
      select jsonb_build_object(
        'issued', count(*),
        'consumed', count(*) filter (where ticket.consumed_at is not null),
        'revoked', count(*) filter (where ticket.revoked_at is not null)
      )
      from public.draw_tickets as ticket
      where ticket.source = 'order_paid'
        and ticket.source_id = v_claim.order_id
    ),
    'refundAccount', (
      select jsonb_build_object(
        'maskedAccount', account.masked_account,
        'maskedHolder', account.masked_holder,
        'purgeAfter', account.purge_after,
        'purgedAt', account.purged_at
      )
      from private.claim_refund_accounts as account
      where account.claim_id = v_claim.id
    ),
    'timeline', coalesce((
      select jsonb_agg(jsonb_build_object(
        'action', entry.action,
        'createdAt', entry.created_at,
        'diff', entry.diff,
        'actorName', (
          select actor.nickname
          from public.profiles as actor
          where actor.id = entry.actor_id
        )
      ) order by entry.created_at, entry.id)
      from public.audit_log as entry
      where entry.target = 'order:' || v_claim.order_id::text
        -- 레거시 감사 액션(admin.order.cancellation_*)도 같은 클레임의 이력이다.
        -- 'claim'만 찾으면 #252 이전 경로로 처리된 건의 타임라인이 비어 보인다.
        and (entry.action like '%claim%' or entry.action like '%cancellation%')
    ), '[]'::jsonb)
  )
  into v_result;

  return v_result;
end;
$$;

revoke all on function public.admin_order_claim_detail(uuid)
  from public, anon, authenticated, service_role;
grant execute on function public.admin_order_claim_detail(uuid)
  to authenticated;

-- ---------------------------------------------------------------------------
-- 12. 환불계좌 파기 잡
-- ---------------------------------------------------------------------------
-- 원문 세 칸만 비우고 행은 남긴다. 행까지 지우면 "계좌를 받았었다"는 사실이
-- 사라져 감사에서 수집 여부를 확인할 수 없다.
create or replace function public.purge_expired_claim_refund_accounts()
returns integer
language plpgsql
volatile
security definer
set search_path = public, pg_temp
as $$
declare
  v_count integer := 0;
begin
  update private.claim_refund_accounts as account
  set
    bank_name = null,
    account_number = null,
    account_holder = null,
    purged_at = now()
  where account.purged_at is null
    and account.purge_after is not null
    and account.purge_after <= now();

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

revoke all on function public.purge_expired_claim_refund_accounts()
  from public, anon, authenticated, service_role;
grant execute on function public.purge_expired_claim_refund_accounts()
  to service_role;

-- UTC 19:30 = KST 04:30. cron.schedule은 이름 기준 upsert라 재적용에 안전하다.
select cron.schedule(
  'purge-expired-claim-refund-accounts',
  '30 19 * * *',
  'select public.purge_expired_claim_refund_accounts()'
);
